filterData: {
  videoTitle: [
    "[mM]ovie",
    "[tT]railer"
  ],
  channelName: [
    "plaqueboymax",
    "maxarchives",
    "MrBeast",
    "Kai Cenat Live",
    "Amp Live",
    "Sidemen",
    "Kai Cenat",
    "Elliot Choy",
    "ur mom ashley",
    "Justin Tse",
    "Luke Eich",
    "Andres Vidoza",
    "Unbox Therapy",
    "THEODORT",
    "Dave2D",
    "Mrwhosetheboss",
    "JOYCA",
    "Michou",
    "SQUEEZIE",
    "Mister V",
    "Mcfly et Carlito",
    "RASKA",
    "Mastu +",
    "maxtouchesgrass",
    "Linus Tech Tips",
    "Marques Brownlee",
    "Snazzy Labs",
    "Joshua Valour",
    "Karl Conrad",
    "JerryRigEverything",
    "The Wall Street Journal",
    "ShortCircuit",
    "SuperSaf",
    "UrAvgConsumer",
    "EXCESSORIZE ME.",
    "JDub",
    "YDN",
    "YDN Jaden",
    "adot",
    "KELWAK",
    "Kelly Wakasa",
    "The Tren Twins",
    "Jesse James West",
    "jedcal",
    "Joma Tech",
    "& They Were Roommates",
    "Karat",
    "Fred Liu",
    "Apple",
    "The Studio",
    "Henry Tran",
    "Kevin Tran 陈科伟",
    "Kevin Tran L'Empereur",
    "HENRY LIVE",
    "SidemenReacts",
    "Live Speedy",
    "AMP",
    "Chunkz",
    "MoreSidemen",
    "Jubilee",
    "Cam Wilder",
    "Adin Live",
    "Adin Ross Clips",
    "Sam Sulek Clips",
    "Sam Sulek Community",
    "ChrisMD",
    "Ramitheicon",
    "Kurzgesagt – In a Nutshell",
    "Brawl Stars",
    "James Scholz",
    "jay skullz",
    "Ruff",
    "Waveform Clips",
    "WVFRM Podcast",
    "Daniels Laizans",
    "Noa Man WORKOUT",
    "Harmen Hoek",
    "Domics",
    "Manga Workout",
    "LE GRAND JD",
    "FastGoodCuisine",
    "Inoxtag",
    "MichouOff",
    "Oliur / UltraLinx",
    "Oliur Online",
    "annemariechase",
    "Fanum Live",
    "Beta Squad",
    "GQ",
    "ESPN",
    "JJ Olatunji",
    "IShowSpeed",
    "KSI",
    "Speedy Boykins",
    "KSIClips",
    "Kai Intern🖤",
    "IMPAULSIVE Clips",
    "Loaf Tube",
    "Kavos",
    "House of Highlights",
    "NBA",
    "Brennen Lin",
    "Maciek Przeniosło",
    "Jim WeGo",
    "workout Calisthenics",
    "Caliversity",
    "Jimmy Kimmel Live",
    "The Tonight Show Starring Jimmy Fallon",
    "Bobbi Althoff",
    "FUTUREMOOD",
    "CaseyNeistat",
    "Gio San Pedro",
    "EheardKing",
    "Lee Lem",
    "Orange Juice Gaming",
    "Keo Tsang",
    "Hafu Go",
    "Luda",
    "WSJ News",
    "Apple Explained",
    "The Apple Circle",
    "TechLinked",
    "Abraham",
    "RDCworld1",
    "Joe Rauth",
    "Brodie Falgoust",
    "Ja Morant",
    "Ryan Trahan",
    "Yesiluvmarii",
    "SirTagCR - Clash Royale",
    "Lavar Johnson",
    "phil cofer",
    "Chris Williamson",
    "Hamza Ahmed",
    "Golden Hoops",
    "Shimon Davis",
    "Kick Game",
    "SHOW NEMOTO",
    "Alex Hormozi",
    "Tristan Jass",
    "Still Watching Netflix",
    "NDL",
    "Binge Society",
    "Niko Clips",
    "Mastu",
    "Magnus Midtbø",
    "KairosTime Gaming",
    "Glarses",
    "UFC",
    "Max Fosh",
    "Mike The Saiyan",
    "Sports Dive",
    "Team USA",
    "ONE Championship",
    "Goku Pump",
    "Duke Dennis",
    "maxplug",
    "DukeDennis LIVE",
    "Drake",
    "Travis Scott",
    "Rihanna",
    "Popcaan",
    "[mM]usic",
    "Darkest Man",
    "More Aj",
    "Harry Pinero",
    "Sky Sports Football",
    "Druski",
    "Agent 00",
    "Awakened Choppa"
  ],
  channelId: [
    ""
  ]
}
